### ISSUE TITLE
how can launch web interface?

### ISSUE THREAD

**Issue by johnfelipe** [Mukosame/Anime2Sketch#10]
how can launch web interface?

**Comment by Mukosame** [comment]
Do you mean this? https://gradio.app/g/AK391/Anime2Sketch

**Comment by johnfelipe** [comment]
Yes how can launch in my droplet with digitalocean public IP?

**Comment by johnfelipe** [comment]
I want to clone and deploy in my public IP droplet server

**Comment by johnfelipe** [comment]
Anyone...

**Comment by johnfelipe** [comment]
im use this commands

    apt update
    apt upgrade
    shutdown -r now

next

    apt install python3-pip
    pip install gradio
    git clone https://github.com/Mukosame/Anime2Sketch.git
    cd Anime2Sketch
    pip install -r requirements.txt

i download this
https://drive.google.com/drive/folders/1Srf-WYUixK0wiUddc9y3pNKHHno5PN6R?usp=sharing

and put in weight folder

##Edit


    gr.Interface(
        sketch2anime, 
        [gr.inputs.Image(type="file", label="Input")], 
        gr.outputs.Image(type="pil", label="Output"),
        title=title,
        description=description,
        article=article,
        examples=[
            ["test_samples/madoka.jpg"],
            ["building.jpg"],
            ["wave.jpg"]
        ], server_name="0.0.0.0").launch(debug=True)

and last one this 

    python3 gradiodemo.py

and show me this

    100%|████████████████████████████████████████| 814k/814k [00:00<00:00, 27.6MB/s]
    100%|████████████████████████████████████████| 250k/250k [00:00<00:00, 3.89MB/s]
    Traceback (most recent call last):
      File "gradiodemo.py", line 16, in <module>
        model = create_model(gpu_ids)
    TypeError: create_model() takes 0 positional arguments but 1 was given

how solved?

**Comment by johnfelipe** [comment]
Do u help me to deploy your app in my linux server?
