### ISSUE TITLE
大佬，请问一下权重文件在哪获取呀

### ISSUE THREAD

**Issue by qingx-plus** [Mukosame/Anime2Sketch#11]
大佬，请问一下权重文件在哪获取呀

**Comment by Mukosame** [comment]
https://drive.google.com/drive/folders/1Srf-WYUixK0wiUddc9y3pNKHHno5PN6R

**Comment by qingx-plus** [comment]
thanks

**Comment by qingx-plus** [comment]
How to convert gif？
