### ISSUE TITLE
ValueError: Unknown resampling filter

### ISSUE THREAD

**Issue by cedro3** [Mukosame/Anime2Sketch#12]
When I run test.py, I get a ValueError: Unknown resampling filter (InterpolationMode.BICUBIC) error in data.py.
To avoid errors
data.py line 96 image_pil = image_pil.resize (output_resize, bic) is
image_pil = image_pil.resize (output_resize, Image.BICUBIC) or
Shouldn't image_pil = image_pil.resize (output_resize, 3)?
This way the error no longer occurs.

**Comment by Mukosame** [comment]
Hi, the bic can be defined as Image.BICUBIC as shown in [this line](https://github.com/Mukosame/Anime2Sketch/blob/master/data.py#L8).
This is to solve [this issue](https://github.com/Mukosame/Anime2Sketch/issues/9). Somehow it creates another issue...

**Comment by brucekomike** [comment]
I get this when I run the example command with Pillow 8.1.2:
 $ python3 test.py --dataroot test_samples/madoka.jpg --load_size 512 --output_dir results/

Traceback (most recent call last):
  File "/home/brucekomike/Python/Anime2Sketch-master/test.py", line 46, in <module>
    save_image(aus_img, aus_path, aus_resize)
  File "/home/brucekomike/Python/Anime2Sketch-master/data.py", line 96, in save_image
    image_pil = image_pil.resize(output_resize, bic)
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 1891, in resize
    raise ValueError(
ValueError: Unknown resampling filter (InterpolationMode.BICUBIC). Use Image.NEAREST (0), Image.LANCZOS (1), Image.BILINEAR (2), Image.BICUBIC (3), Image.BOX (4) or Image.HAMMING (5)

**Comment by brucekomike** [comment]
From this web site
[https://pretagteam.com/question/pil-valueerror-unknown-resampling-filter-how-to-resize-images-uploaded-on-flask](url)
I've get that 'Pillow >= 2.1.0 no longer supports “import _imaging”. Please use “from PIL.Image import core as _imaging” instead.'
I'll try to use the Pillow == 2.1.0 instead of 8.1.2

**Comment by brucekomike** [comment]
When I am using pillow 2.1.0
I get "oserror decoder jpeg not available".

**Comment by alimalls** [comment]
> I get this when I run the example command with Pillow 8.1.2: $ python3 test.py --dataroot test_samples/madoka.jpg --load_size 512 --output_dir results/
> 
> Traceback (most recent call last): File "/home/brucekomike/Python/Anime2Sketch-master/test.py", line 46, in save_image(aus_img, aus_path, aus_resize) File "/home/brucekomike/Python/Anime2Sketch-master/data.py", line 96, in save_image image_pil = image_pil.resize(output_resize, bic) File "/usr/lib/python3/dist-packages/PIL/Image.py", line 1891, in resize raise ValueError( ValueError: Unknown resampling filter (InterpolationMode.BICUBIC). Use Image.NEAREST (0), Image.LANCZOS (1), Image.BILINEAR (2), Image.BICUBIC (3), Image.BOX (4) or Image.HAMMING (5)

python3 -m pip install --upgrade Pillow

**Comment by gongsuming** [comment]
> I get this when I run the example command with Pillow 8.1.2: $ python3 test.py --dataroot test_samples/madoka.jpg --load_size 512 --output_dir results/
> 
> Traceback (most recent call last): File "/home/brucekomike/Python/Anime2Sketch-master/test.py", line 46, in save_image(aus_img, aus_path, aus_resize) File "/home/brucekomike/Python/Anime2Sketch-master/data.py", line 96, in save_image image_pil = image_pil.resize(output_resize, bic) File "/usr/lib/python3/dist-packages/PIL/Image.py", line 1891, in resize raise ValueError( ValueError: Unknown resampling filter (InterpolationMode.BICUBIC). Use Image.NEAREST (0), Image.LANCZOS (1), Image.BILINEAR (2), Image.BICUBIC (3), Image.BOX (4) or Image.HAMMING (5)

Just replace bic with 3 in image_pil = image_pil.resize(output_resize, bic).
