### ISSUE TITLE
how to train for my own dataset

### ISSUE THREAD

**Issue by Johnson-yue** [Mukosame/Anime2Sketch#13]
Hi， thanks for your sharing , I want to train my own dataset using this network

I see in readme for training in AODA, but  AODA repo also has nothing about how to train 。。。

**Comment by Mukosame** [comment]
Hi, thanks for your interest in this work!
I haven't finished cleaning the training code for AODA, since I am busy in graduating recently. I will let you know as soon as I finish.

**Comment by Mukosame** [comment]
Hi @Johnson-yue , the complete training codes of AODA have been uploaded to GitHub. Happy holiday!
