### ISSUE TITLE
How can we make it work on normal images?

### ISSUE THREAD

**Issue by Nerdyvedi** [Mukosame/Anime2Sketch#2]
Hi, I would like to convert normal face images to sketch.  Would a model trained on ffhq dataset perform well with normal images? Have you tried something like this before?

**Comment by Mukosame** [comment]
Hi, I haven't tried this before. The major problem is that I don't have such well-aligned face sketch data like ffhq. I know some previous works (https://github.com/yiranran/APDrawingGAN, https://github.com/yiranran/APDrawingGAN2) that collected data through collaborating with artists. You could try their models :)
