### ISSUE TITLE
Artifacts in result sketch

### ISSUE THREAD

**Issue by Tia-Cheung** [Mukosame/Anime2Sketch#21]
Hi

Thanks for your great work.

When I test on my own dataset, sometimes it will show some artifacts in darkness place.
Do you have any good suggestions to fix it? 
![artifact](https://user-images.githubusercontent.com/68932652/159424037-c43c3e38-2f2c-4c5f-a981-53e5d9c2a981.jpg)

**Comment by Mukosame** [comment]
Hi @Tia-Cheung , sorry that the network fails when there are dark regions when the contrast is very low. Currently I have no way to fix it, but the failed patterns are fixed -- maybe we could filter out such patterns with post-processing.

**Comment by Tia-Cheung** [comment]
Can you give some advice about the post-processing? 
I try to do contrast pre-increase and some noise reduction, can‘t clean all the failed pattern.

**Comment by silenye** [comment]
I have the same problem too, is there any solution?
