### ISSUE TITLE
line extraction but with colored lines

### ISSUE THREAD

**Issue by koke2c95** [Mukosame/Anime2Sketch#22]
Hi, thanks to great works.

tho found this project has been stalled for a year

can it do line extraction but with colored lines (mark) , train model on multi-colour lines pairs ?

In fact, in animation production, called 色トレス, need work that tracing the scanned paper drawing into digital
> the tracing easy to coloring (compare to illustration making), tracing following coloring reference to standardize lines colour, like [solid line, shadow, highlight mark](https://labs.gree.jp/blog/2020/03/20525/)

**Comment by Mukosame** [comment]
Hi @koke2c95 , thanks for your interest!
I haven't tried it one colored lines, since it is not easy to get such training data from internet. I can propose a very hacky way---use our generated line extraction as a binary mask on the original input, and keep the colors of the original lines.
Thanks for introducing the 色トレス to me!

**Comment by koke2c95** [comment]
@Mukosame luckly, early days I found a artist

his/her do screencap tracing to animation drawings [アニメ原画 style](https://twitter.com/tyuuboutyauyo/status/425651466838085632) [coloring mark lines 色トレス線](https://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q11143575606). and re-colored drawings with own color coordination.

his/her post cumulative large quantities, with works tagged, some newer with name and episode number

here you can ask [p](https://www.pixiv.net/users/2613692/illustrations) [t](https://twitter.com/haruhigurasi)

also there large quantities [minimalist anime vectored](https://yande.re/post?page=4&tags=vector_trace+transparent_png+rating%3Asafe) by greenmapple17 might useful [a](https://imgur.com/gallery/UWEAI) [b](https://imgur.com/gallery/edimP)
