### ISSUE TITLE
Artifact-free version of model

### ISSUE THREAD

**Issue by RE-N-Y** [Mukosame/Anime2Sketch#31]
# Overview

Right now, this model has issues in dark / low contrast regions #21. I've made a version of the model which significantly reduces the artifacts of this model without degrading performance on existing images.
Below are a couple of examples model outputs

# Normal image
## Image
![image](https://github.com/Mukosame/Anime2Sketch/assets/19684973/e7bfab53-7631-406f-bcf3-b4e3dd8e6d29)
## Original
![image](https://github.com/Mukosame/Anime2Sketch/assets/19684973/e4d43b7d-c564-42d7-bbb4-02008e30d1bc)
## Improved
![image](https://github.com/Mukosame/Anime2Sketch/assets/19684973/9333a468-a429-4a8b-b91b-22bc8cc295ad)

# Dark image
## Image
![image](https://github.com/Mukosame/Anime2Sketch/assets/19684973/1e82b63f-fed9-42bd-a475-6a70d8474b0c)
## Original
![image](https://github.com/Mukosame/Anime2Sketch/assets/19684973/e078b875-c01e-4d39-a17c-66224352dc6b)
## Improved
![image](https://github.com/Mukosame/Anime2Sketch/assets/19684973/0a27a262-bda4-41d6-aa42-68ad0307f33b)

Of course, the model outputs aren't perfect... but if the author of the repository or anyone is interested. Would be glad to write a PR or share methods, weights and code.

**Comment by Mukosame** [comment]
Hi @RE-N-Y , thanks for showing these inspiring results! Feel free to make a PR (maybe an easiest way is to add your download link [here](https://github.com/Mukosame/Anime2Sketch/blob/master/README.md?plain=1#L37)). I will be more than happy to merge it :)

**Comment by RE-N-Y** [comment]
Thanks! I will make a PR in couple of days.

**Comment by RE-N-Y** [comment]
Closed with #32
