### ISSUE TITLE
Error when using Gradio

### ISSUE THREAD

**Issue by shandytp** [Mukosame/Anime2Sketch#5]
Hello, just like the title said. I can't perform Anime2Sketch using the Gradio demo website and I got an error.

![image](https://user-images.githubusercontent.com/49873935/118232251-797bb800-b4ba-11eb-825a-bd6f6a00fbd4.png)

And I can't use the demo image from the website.

![image](https://user-images.githubusercontent.com/49873935/118232352-9dd79480-b4ba-11eb-8c8c-e5f06358929f.png)

I don't know it is a bug or just my internet because I already try to delete the cookies and I still have that trouble.

Thank you

**Comment by Mukosame** [comment]
Hi @AK391 , I also got the same problem when testing just now. Seems like the framework works but cannot load the relevant files correctly. Would you mind to check if there's any issue with gradio?

**Comment by AK391** [comment]
@Mukosame sorry for the late reply, we had some downtime issues last week it should be fine now
